### ISSUE TITLE
Define latitude and longitude limits in trajLevel, trajPlot and trajCluster

### ISSUE THREAD

**Issue by rrbuchholz** [davidcarslaw/openair#13]
I recently updated openair and one of my plot commands isn't working the same way. In particular I can't seem to set my own limits on trajLevel, trajPlot and trajCluster. I originally did this with xlim and ylim, and then with the previous openair update I changed to including:
subset(mydata, lat > -70 & lat < -5 & lon > 90 & lon < 180)

The subset method works if I want to plot an area smaller than the default map plot, but no longer if I want a larger area than the default. Do you have any advice? Is there another argument I should be using?

Cheers,
Rebecca

**Comment by davidcarslaw** [comment]
You are quite right. The changes to the map projections have messed this up because all the data are transformed to very different map units. Setting the xlim/ylim turned out to be trickier than I first thought because some map projections give very different transformations to cartesian coordinates (can't just transform the 4 corners). For now you can manually play around with the limits e.g.

    traj <- importTraj()
    trajPlot(head(traj, 3000))

now constrain the longitude to zoom in a bit:

    trajPlot(head(traj, 3000), xlim = c(-0.1, 0.1))

I will have another look at this and develop a more robust solution.

**Comment by rrbuchholz** [comment]
Thanks for the clarification. I found the area I want with "mercator" projection was defined by:
xlim= c(1.5,3.2), ylim = c(-1.2,-0.1)
It's a good fix for now.

**Comment by davidcarslaw** [comment]
I have now hopefully improved the xlim/ylim in trajectory plots. You can either build the package as described on Github or download the appropriate file here https://www.dropbox.com/sh/x8mmf5d54wfo5vq/AACpKqsrPkTC0guiu5ftiKNna?dl=0

Let me know if you have any problems...
