### ISSUE TITLE
add textures to windRose/pollutionRose (feature request)

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [davidcarslaw/openair#140]
In an attempt to improve visibility of windrose/pollutionRose plots with people who may be visually impaired, specifically people who may be colorblind, I am requesting that an option, texture.fill=T be added to windrose/pollutionRose plots. Hopefully something like this example can be added to these functions fairly easily:

http://www.r-graph-gallery.com/193-change-texture-of-barplot-with-density/

Thank you for your time.

**Comment by Agriculturist** [comment]
The openair package uses trellis based graphics.  With trellis graphics 'hatching' was deliberately left out because it is thought to create an optical illusion which distorts the data. [*link](https://markmail.org/message/cj23tnsgsobs4mbu?q=list:org%2Er-project%2Er-help+lattice+hatching#query:list%3Aorg.r-project.r-help%20lattice%20hatching+page:1+mid:heoljigs5uurpr47+state:results)

A very simple approach is available to make a windrose colorblind safe.

(1) [Grab a colorblind safe pallette](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/)

`cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")`

(2) plot the wind rose using a different colorblind safe scheme.  

 `windRose(mydata, paddle = FALSE, dig.lab = 0, cols = cbPalette)`

![image](https://user-images.githubusercontent.com/8715156/38754476-040f3c52-3f30-11e8-9994-db9c33988751.png)

An easy enough solution would be to add a colorblind safe palette to the openColours() function.  This function would need to throw a warning if too many intervals are used. 

This is a good idea because many government agencies are required to make plots which take into account people who may be visually impaired.

**Comment by jack-davison** [comment]
Closing as Jerry has got it spot on, with an additional note that `openColours()` supports all of the colourblind friendly "brewer" palettes (https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/#show-only-colorblind-friendly-brewer-palettes). e.g., "Dark2".

```r
openair::pollutionRose(openair::mydata, "nox", cols = "Dark2")
```

![image](https://user-images.githubusercontent.com/45171616/216985631-b4c0e908-8f91-410f-af29-ff869484ca16.png)
