### ISSUE TITLE
Summary Data for Short Term Air Quality Strategy Comparison

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/openair#183]
Good morning all, 

Does anyone know how I can quickly generate the frequency of measurements greater than a certain value.  I have a detailed dataset downloaded from KCL LAQN consisting of a number of monitoring sites. 
 The measurements consist of hourly NO2 concentrations.  I would like to know the number of times (number of hours) each site exceeded the value of 200 ug/m3 for NO2.  This is so I can compare it to the UK national standards.

I know how to subset my data and can extract this information to excel to get my answer, however it would be really useful if I could generate this summary data in R for a quick answer.  

Thanks

**Comment by jack-davison** [comment]
Hi,

I appreciate this is an old issue so I imagine you've found your solution elsewhere, but this is something that you could achieve with more generic R packages rather than with `openair`. I'd recommend giving [R for Data Science](https://r4ds.had.co.nz/) a read if you'd like to learn more "core" R skills.

Closing as this issue is stale as of Jan 2019, but feel free to reopen/raise a new issue if you do get stuck.

``` r
library(openair)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# import data
test_data <- importAURN(c("my1", "kc1"), year = 2000:2020)

# calculate number of times no2 is >= 200
no2_summaries <- 
  test_data %>%
  group_by(site, year = lubridate::year(date)) %>%
  summarise(n_over = sum(no2 >= 200, na.rm = TRUE),
            total = n()) %>%
  mutate(frac = n_over / total)
#> `summarise()` has grouped output by 'site'. You can override using the
#> `.groups` argument.

# plot?
library(ggplot2)

ggplot(no2_summaries, aes(x = year, y = frac)) +
  geom_col() +
  facet_wrap(vars(site)) +
  scale_y_continuous(labels = scales::label_percent()) +
  theme_bw() +
  labs(x = NULL, y = quickText("% of hours where NO2 is\ngreater than 200 ug/m3"))
```

![](https://i.imgur.com/BD1omvk.png)

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
