### ISSUE TITLE
Error using function importKCL()

### ISSUE THREAD

**Issue by UzielGonzalez** [davidcarslaw/openair#215]
Hi, 

Last few days I've been using the function importKCL(), it was working  but today after typing for instance:
> mary <- importKCL(site = "my1", year = 2000:2009)
 
I've got this error:

Error in load(con) : 
  the input does not start with a magic number compatible with loading from a connection

This is the version used:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes  

Regards,
Uziel

**Comment by davidcarslaw** [comment]
Hi Uziel

Thanks for the report. I think this is because R changed the format of its data objects in a recent version and old data will not be compatible with recent versions of R. I suspect the King's College server uses a very old version of R. I will investigate.

In the meantime you can access the data for that site by

` mary <- importAURN(site = "my1", year = 2000:2009)`

Note that the next release of openair will have access to far more sites too. You can install the GitHub version and checkout `importEurope` and `importAQE`. Also, check out Stuart Grange's [saqgetr](https://github.com/skgrange/saqgetr) package.

All the best
David

**Comment by UzielGonzalez** [comment]
Thanks for you suggestions, the function and the package are great! you've made my work easier.
