### ISSUE TITLE
create scatter plot matrix with openair and hexbin

### ISSUE THREAD

**Issue by metroid2012** [davidcarslaw/openair#236]
I've worked with the openair and hexbin packages to create two scatter plots with the help of the scatter plot function commands:
scatterPlot(mydata, x ="Observed" , y = "Model1",xlab=10, ylab=10,method = "hexbin",mod.line=T,auto.text=F, col = "jet", xbin = 30)

scatterPlot(mydata, x ="Observed" , y = "Model2",xlab=10, ylab=10,method = "hexbin",mod.line=T,auto.text=F, col = "jet", xbin = 30)
I've got the scatter plots, but if I want to put them into one plot and with one color counts to get something similar to this:How should i proceed?
![FGiun](https://user-images.githubusercontent.com/59290689/90345858-3ddfba80-e01c-11ea-9afb-9caa4818c5c9.png)

**Comment by mauriciorozas97** [comment]
Hello,

I don't know if this is the correct way to cover the problem you describe, but at least it worked for me. I am attaching screenshots of the dataframes and the code I used.


PS: The "mod1" and "mod2" data frames are the same because they come from the same model. Just use them as an example for the exercise.

I hope I've helped.




<img width="485" alt="Ayuda" src="https://user-images.githubusercontent.com/61034062/91418782-9edb6f80-e820-11ea-8f2e-127ccb2672b4.png">

<img width="621" alt="PLOTDEF" src="https://user-images.githubusercontent.com/61034062/91418921-caf6f080-e820-11ea-96a2-5ed955a28a04.png">

**Comment by jack-davison** [comment]
You'll need to reshape your data first. See [article here](https://r4ds.had.co.nz/tidy-data.html#pivoting). Going to close as this issue has been stale for a while, but feel free to reopen with a [reproducible example](https://www.tidyverse.org/help/) if you struggle. Cheers, Jack.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(openair)

scatterPlot(
  mydata,
  x = "no2" ,
  y = "nox",
  xlab = 10,
  ylab = 10,
  method = "hexbin",
  mod.line = T,
  auto.text = F,
  col = "turbo",
  xbin = 30
)
```

![](https://i.imgur.com/RjkrJpj.png)

``` r

scatterPlot(
  mydata,
  x = "no2" ,
  y = "o3",
  xlab = 10,
  ylab = 10,
  method = "hexbin",
  mod.line = T,
  auto.text = F,
  col = "turbo",
  xbin = 30
)
```

![](https://i.imgur.com/5odpQik.png)

``` r

mydata %>%
  tidyr::pivot_longer(c(o3, nox), names_to = "pollutant", values_to = "concentration") %>%
  scatterPlot(
    x = "no2",
    y = "concentration",
    xlab = 10,
    ylab = 10,
    method = "hexbin",
    mod.line = TRUE,
    auto.text = FALSE,
    col = "turbo",
    xbin = 30,
    type = "pollutant",
    y.relation = "free"
  )
```

![](https://i.imgur.com/IfxRb9i.png)

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
