### ISSUE TITLE
percentileRose looking strange on sparse wd data

### ISSUE THREAD

**Issue by JasperSch** [davidcarslaw/openair#245]
Hi,

The `percentileRose()` looks a bit weird when there are only few values available for certain wind directions.

To improve the user friendliness, I was thinking about a warning of the following kind:
`Warning: less then N observations detected for wd x, it is advised  to increase the angle for a proper display.`

Are there any other options to improve the display and/or throw warnings when there is not enough data available?

Thanks in advance!

MWE:
```
library(openair)
df <- importAURN(site = "kc1", year = 2011:2012)
dfSmall <- df[1:50,]

openair::percentileRose(
    dfSmall,
    percentile = 95
)
hist(dfSmall$wd, seq(0,360,10))

```
![image](https://user-images.githubusercontent.com/49677239/97023699-2b22be00-1556-11eb-9879-6a47f728e616.png)

![image](https://user-images.githubusercontent.com/49677239/97023799-53122180-1556-11eb-9a8c-552eab7f80a5.png)

**Comment by davidcarslaw** [comment]
Thanks for the report. I will take a look.

**Comment by davidcarslaw** [comment]
For now you can do

```
openair::percentileRose(
    dfSmall,
    percentile = 95, fill = FALSE, mean = FALSE
)
```

The problem is when there is only one value in a wind sector then all statistics are the same - so the line should not return to the origin in the way these plots are developed. Adding the option `smooth=TRUE` might look more like what you are after?

```
openair::percentileRose(
    dfSmall,
    percentile = 95, smooth = TRUE
)
```

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1236491/107393004-2debf380-6af2-11eb-955b-5eb525e96a20.png">
