### ISSUE TITLE
PolarPlot -- Extreme concentrations

### ISSUE THREAD

**Issue by ABDOU-21** [davidcarslaw/openair#248]
Dear Dr. Carslaw,

Sorry for taking some of your time. I am a new user, and I would appreciate to get some answers to my concern.

I have used the PolarPlot function on a dataset, and I keep getting some "extreme concentrations" to which I am unable to find an explanation. I have cleaned my data and removed the outliers but what I called "extreme concentrations" still appear on the plot.

This is the code I used:

polarPlot(dataset, pollutant = "nox", col = "jet", key.position = "bottom",
          key.header = "Mean NOx (mg/m3)", key.footer = NULL)

I would greatly appreciate your guidance. 

Here are attached the dataset I have used and the result I got.

![PolarPlot](https://user-images.githubusercontent.com/79007782/107850114-f5724f80-6e3a-11eb-97a7-205147632a25.png)

[dataset.docx](https://github.com/davidcarslaw/openair/files/5975647/dataset.docx)

**Comment by davidcarslaw** [comment]
Hi

These are not extreme concentrations. It's caused by having isolated wind speed - direction values e.g. at wd ~ 110 degrees and ws = ~5 m/s. Usually when this happens it is because of poor meteorological data or some weird conditions. You can also try the option `min.bin = 2`, which will ignore these single points...

**Comment by ABDOU-21** [comment]
Thank you very much for your reply. I will look into that and try the min.bin option.
