### ISSUE TITLE
How to use break axis option.

### ISSUE THREAD

**Issue by itspuneetv** [davidcarslaw/openair#309]
I would like to break the y-axis of the timeplot function.  Could you please how can I do to replicate something like below?

![image](https://user-images.githubusercontent.com/50046053/203730030-bfd4bf51-8dd7-4422-a226-b78a49b3ad60.png)

**Comment by jack-davison** [comment]
Hi Puneet,

Breaking the y-axis like that is often a [bad idea](https://www.addtwodigital.com/add-two-blog/2021/11/1/rule-26-dont-use-broken-axes-or-bars) because it breaks the relationship between chart space and the values the chart geometry is meant to represent.

Right now it isn't possible to break the y-axis using `{openair}`. However, they may be useful alternatives, such as the use of the `type` argument, using a different chart type, or transforming the y-axis in some other way (e.g., a log transform).

Have a look at some of the examples in the [openair book](https://bookdown.org/david_carslaw/openair/time-plot.html#examples-of-time-series-plotting) or, alternatively, feel free to post your chart without the axis break and we can see if `{openair}` can provide an alternative strategy.

Cheers,
Jack
