### ISSUE TITLE
Remove big blank space between taylor diagram in grid.arrange()

### ISSUE THREAD

**Issue by stanleesocca** [davidcarslaw/openair#311]
Hi? 
I've been using the openair and testing its taylor diagram for plotting and thanks for your work. I have a little problem regarding a lot of space in the between two rows of plot when the output of TaylorDiagram() is used inside gridExtra().

 See picture below. 
![image](https://user-images.githubusercontent.com/31194250/204866763-8f53729e-2202-4489-8732-8fb3bd23af43.png)

I don't how to solve it and I have try using the par.settings function, another grid arrangement package (cowplot) etc. Can you help with this or do you have an idea on how I might solve it. 

Thanks.

**Comment by jack-davison** [comment]
Hi,

This may just be a case of playing with the ratio of width:height to make them stick together. This is a relatively common issue with grid-based graphics with fixed aspect ratios. I had some success creating a 2x3 matrix of plots by using a 2:1 ratio:

```r
plt <- TaylorDiagram(mydata, "nox", "no2", group = "weekend")
plt <- plt$plot

cowplot::plot_grid(plt, plt, plt, plt, plt, plt)
```

![image](https://user-images.githubusercontent.com/45171616/217035404-b1af67c4-31b1-4617-b6e3-2db8b431c461.png)

The above screenshot was taken using RStudio > Export to clipboard, with width of about 1200 and height of 600.

You could also play with the `key.pos` argument, as the keys being on the right hand side (rather than the top) may be making the plot unnecessarily wide.
