### ISSUE TITLE
[Question]: Can openair handle hour beginning/ending timestamps?

### ISSUE THREAD

**Issue by mjholm4242** [davidcarslaw/openair#355]
Depending on the jurisdiction, AQM data is either timestamped hour beginning or hour ending.  13:00-14:00 would be 14:00 if hour ending.  I believe the EPA and the Environment and Climate Change Canada want hour ending.

When I use the timeAverage function to create daily averages, it takes data from 00:00 to 23:00.  If the data I am compiling is using hour ending, this function is giving me the wrong average.

I can obviously adjust all my timestamps by one, but I am wondering if there is a build in switch/setting to account for hour beginning/ending?

**Comment by mooibroekd** [comment]
I think the best approach here is basically to stop using only hour beginning or hour ending, and use them both,.Since we adapted the procedure that we set start and end date times for each measurements we never have had any discussions about their meaning.

The only difference is now, because {openair} expects the parameter to be called `date` is that we rename `start_date` to `date` and be done with it. In cases where we know the data is provided with either start or ending date times we make sure our import routine fixes that.

**Comment by jack-davison** [comment]
Hi @mjholm4242, `{openair}` does not have any options currently for "hour ending" dates, and its not planned to introduce a "toggle" for this at the moment. All the toggle would do is remove an hour from the dates regardless.

As @mooibroekd mentions, it may be a good idea to create two columns - `date` and `date_end` - for use in `{openair}`, as that will eliminate all confusion. It may also be useful if you are using data from different jurisdictions with different rules together, because everything will be stored consistently and could be bound together into one dataframe if desired.

Example below of how you might do that:

``` r
dummydata <- data.frame(date = c("2023-09-01 05:00:00",
                                 "2023-09-01 06:00:00",
                                 "2023-09-01 07:00:00")) |>
  dplyr::mutate(date = lubridate::ymd_hms(date))

dummydata
#>                  date
#> 1 2023-09-01 05:00:00
#> 2 2023-09-01 06:00:00
#> 3 2023-09-01 07:00:00

dummydata |> 
  dplyr::rename(date_end = date) |> 
  dplyr::mutate(date = date_end - lubridate::hours(1),
                .before = date_end)
#>                  date            date_end
#> 1 2023-09-01 04:00:00 2023-09-01 05:00:00
#> 2 2023-09-01 05:00:00 2023-09-01 06:00:00
#> 3 2023-09-01 06:00:00 2023-09-01 07:00:00
```

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
