### ISSUE TITLE
import function

### ISSUE THREAD

**Issue by dos7408** [davidcarslaw/openair#372]
### Bug description

After updating the openair package to ‘2.18.0’  two weeks ago I couldn't anylonger load data by the usual "import" command lines employed along several years. For instance typing:

 mydata <- import("example data long.csv")

I get the message: Error in import ("example data long.csv")  cannot find function "import" 

Has anything changed in Openair regarding this function?

Thank you

### Openair version

‘2.18.0’

**Comment by jack-davison** [comment]
`import()` was a bit of a legacy function and isn't currently supported by `{openair}`.  This is because there are now loads of tools out there for reading csv and other files using R.

In base R you can use `read.csv()`.

There are also whole packages dedicated to reading rectangular data - for example [readr](https://readr.tidyverse.org/index.html).

If you're having trouble, feel free to attach your CSV or other file and we can take a look.

Jack

(duplicate of https://github.com/davidcarslaw/openair/issues/366)

**Comment by dos7408** [comment]
Thank you Jack, very clear. It might be useful make that explicit in Openair manuals.

Cheers,

Gian

**Comment by jack-davison** [comment]
No worries!

We've got it on the list to add a section on reading local data to the openair book, when time permits! https://github.com/davidcarslaw/openair-book/issues/10

Jack
