### ISSUE TITLE
code to prepare RData files from Airbase

### ISSUE THREAD

**Issue by jobonaf** [davidcarslaw/openair#52]
Could you share the code you used to prepare *.RData files stored here?
http://www.erg.kcl.ac.uk/downloads/Policy_Reports/airbase/
Thank you
Giovanni

**Comment by jack-davison** [comment]
Hi Giovanni,

I'm closing this stale issue as its not been looked at in many years. Please feel free to reopen if you're still interested in Airbase data, though note that your URL now redirects elsewhere as the KCL website has since been updated.

The [saqgetr](https://github.com/skgrange/saqgetr) package may be of interest to obtain Airbase AQ data.

Cheers
