### ISSUE TITLE
aqStats error requiring POSIX class argument for o3

### ISSUE THREAD

**Issue by stevecrawshaw** [davidcarslaw/openair#66]
This only happens for o3
reproducible code
rm(list=ls(all=TRUE))
library(openair)
brs8 <- importAURN(site = "brs8", year = 2015)

no2stats <- aqStats(brs8, pollutant = "no2")
#works
o3stats <- aqStats(brs8, pollutant = "o3")
#fails with this msg
#Error in fit_to_timeline(date, class(object)[[1]], simple = simple) : 
#class argument must be POSIXlt or POSIXct

pm10stats <- aqStats(brs8, pollutant = "pm10")
#works

**Comment by davidcarslaw** [comment]
thanks - seems that `importAURN` gets the date class wrong (as far as the package lubridate expects anyway). Hopefully fixed this - but you will need to download the `brs8` data again and install directly from GitHub if you are able to?

**Comment by stevecrawshaw** [comment]
Thanks, I know I need devtools for this, which is installed, but can you provide me with the code to install from github please?
Thanks
steve

**Comment by davidcarslaw** [comment]
If you have a look [here](https://github.com/davidcarslaw/openair) there are installation instructions. Basically you can just do:

````
require(devtools)
install_github('davidcarslaw/openair')
````

BUT - on Windows you will need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) because `openair` needs compilers for the C++ code it contains. I also give links to pre-made packages but I'm not at a Windows machine at the moment and will have to remake the package later on...
