### ISSUE TITLE
timeAverage 

### ISSUE THREAD

**Issue by LunaMaan** [davidcarslaw/openair#86]
The timeAverage function calculates hourly averages assuming the data is provided as time beginning i.e. the values 10:00, 10:10, 10:20, 10:30... are used to calculate the hourly average for 10:00, whereas the values provided by air quality/weather station instruments in New Zealand makes use of time ending stamps, which means that the values mentioned above will be used to calculate the average for 11:00. Is there a way to include the option for time ending/time beginning in the timeAverage function in order to change the way in which hourly averages are computed to match the instruments?

Here is an example:

timeAverage currently calculates the hourly average for timestamp 10:00 from the following timestamps (for a 10-minute dataset): 10:00, 10:10, 10:20, 10:30, 10:40, 10:50

Instruments will calculate the hourly average for 10:00 from the following timestamps: 09:10, 09:20, 09:30, 09:40, 09:50, 10:00

It would be nice to have the option to calculate averages with timeAverage similar to the instrument.

Thanks for the great package, it is very useful and I use it often, good work!!!!

**Comment by davidcarslaw** [comment]
`timeAverage` does indeed consider time beginning - but so does R in general. I think it is safer to convert the data to time beginning otherwise you may experience problems elsewhere. If your data are correctly in POSIXct format, you can simply subtract some time as times are expressed in seconds. So for hourly data, something like:

`mydata$date = mydata$date - 3600`

The problem of 'fixing' this in openair is that not all functions would be aware of how the time was expressed...
