### ISSUE TITLE
confidence intervals in timeVariation()

### ISSUE THREAD

**Issue by rs028** [davidcarslaw/openair#96]
Hello, I have R version 3.3.1  and openair version 1.9.
I think there is an issue with the timeVariation function. It seems that the confidence intervals vary slightly if the function is run multiple times (with the same settings and on the same data).
Below are two examples, I think the difference may be more noticeable if the data are more scattered. Thank you

<img src="https://cloud.githubusercontent.com/assets/7703778/20538895/0717da96-b0eb-11e6-85f4-f051c350737a.png" width="300" height="300"> <img src="https://cloud.githubusercontent.com/assets/7703778/20538894/07172cae-b0eb-11e6-9226-a1b671f8baa6.png" width="300" height="300">

**Comment by maxbre** [comment]
I guess a consequence of the bootstrap method used?

**Comment by maxbre** [comment]
Please could you provide some insights about the used method for bootstrapping confidence intervals? Thank you

**Comment by davidcarslaw** [comment]
Yes, the variation is due to bootstrap resampling, so there will be some differences. The calculation is based on random sampling with replacement and then the calculation of the 2.5 and 97.5% values. You can reduce the variation by increasing the number of bootstrap samples (default B = 100). 

You should be able to make the function reproducible though through `set.seed` e.g.

```
set.seed(100)
timeVariation(selectByDate(mydata, year = 1999), B = 5)

set.seed(100)
timeVariation(selectByDate(mydata, year = 1999), B = 5)
```

should give the same output.

**Comment by rs028** [comment]
Okay, good to know. Since this is not an error, I am closing the issue. Thank you.
